version: "3"

services:
  database:
    image: mysql
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dump
    ports:
      - "9906:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=mysql
      - PMA_PASSWORD=mysql
    links:
      - "database:db"
    ports:
      - "9980:80"
    depends_on:
      database:
        condition: service_healthy
